// Env is globally declared by worker-configuration.d.ts (generated by `wrangler types`)

export interface AgentState {
  eventCount: number;
  lastEvent: {
    type: string;
    action: string;
    timestamp: string;
  } | null;
}

export interface StoredEvent {
  id: string;
  type: string;
  action: string;
  title: string;
  description: string;
  url: string;
  actor: string;
  payload: string;
  installation_id: number | null;
  timestamp: string;
}
